apiVersion: v2
name: exoscale-exporter
description: A Exoscale exporter.
maintainers:
  - email: nguyen_marc@live.fr
    name: Marc Nguyen
type: application
version: 0.1.0
appVersion: '1.0.2'
sources:
  - https://github.com/SquareFactory/exoscale_exporter
